default:
  tags:
    - CREMI 
    - Focal/Fossa

stages:
  - build
  - test
  - coverage

buid-job1:
  stage: build
  script :
    - pip install coverage


test-job1:
  stage: test
  script :
    - python3 -m unittest -v tests/test_FileRepo.py
    - python3 -m unittest -v tests/test_Point.py

coverage-job1:
  stage: coverage
  script :
    - coverage run -m unittest
    - coverage run --source=tests -m pytest tests/test_FileRepo.py
    - coverage run --source=tests -m pytest tests/test_Point.py
    - coverage report -m



