default:
  tags:
    - CREMI 
    - Focal/Fossa

stages:
  - build
  - test
  - coverage

buid-job1:
  stage: build
  script :
    - pip install coverage


test-job1:
  stage: test
  script :
    - python3 -m unittest -v src/models/test_Point.py

coverage-job2:
  stage: coverage
  script :
    - coverage run -m unittest
    - coverage run --source=Parser -m pytest src/models/test_Point.py
    - coverage report -m
